pylerSM/YouTubeBackgroundPlayback

src/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

Should fix #18 #16 #14 and maybe others

Fixes #14 #16 #18

---

src/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/33

fix to support various YouTube builds and minor updates

---

res/values-ko/strings.xml

New Korean translation for just description! :D

Korean translation for description!

---

build.gradle
java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
res/values-zh-rTW/strings.xml

The Java code has mixed indents (spaces and tabs) and some other minor styling issues that this PR cleans up. Along that, fixes for obfuscation detection and version updates are included. Simple as that.

Clean up Java code

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

This PR aims to adds support for 11.15.55, 11.16.62 and 11.17.52. Nothing else changed.

Bump for 11.17.52

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

This PR aims to adds support for 11.18.52. Nothing else changed.

Bump for 11.18.52

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
youtube_hooks.json

This PR aims to adds support for 11.20.54. Nothing else changed.

Bump for 11.20.54

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
youtube_hooks.json

This PR aims to adds support for 11.21.53. Nothing else changed.
cc: @pylerSM @th3an7

Bump for 11.21.53

---

res/values-hu/strings.xml

Create Hungarian translation

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
youtube_hooks.json

This PR aims to adds support for 11.22.54 and 11.22.56. Nothing else changed, no way yet of making the notification appear only when application is hidden.
cc: @pylerSM @th3an7

Bump for 11.22.56

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
youtube_hooks.json

This PR aims to adds support for 11.23.56. Nothing else changed.
cc: @pylerSM @th3an7

Bump for 11.23.56

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

This commit simply adds support for version 11.25.55 of the YouTube application. Rejoice!

Add support for version 11.25.55

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
youtube_hooks.json

Update for YT 11.29.55 + typo fix

Update for YT 11.29.55

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

Update for YT 11.33.55

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
youtube_hooks.json

Update for YT 11.33.58

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java
youtube_hooks.json

Update for YT 11.39.56

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

Update for YT 11.41.56

---

AndroidManifest.xml
README.md
java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

The commit message and the code describe this all much better, but essentially:
1. Hooks get stored in a JSON file.
2. Application pulls in that JSON file.
3. Magic rules that are in the JSON file get applied.
All feedback is appreciated. / @pylerSM @th3an7 
By the way, can we have a v2.0.0 release for when we merge this change?

Dynamically load the hook details

---

assets/hooks-1.json

Update for YT 12.07.63 - Not sure about "cip" class - it is visible in code (in class "cil") but it redirects to previous version (12.07.61)

Update for YT 12.07.63

---

.gitignore
build.gradle
res/values-de/strings.xml

I did not translate the app's name because it's almost impossible to translate it in a good way.
Also added AndroidStudio files to gitgnore.

Added a german translation and a fix for a lint build error.

---

java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java

I've made small changes to allow one module to be compatible with both yt apps. URL to download hooks will be matched by package name.
I've set the hooks-music.json from yt-music branch as download URL. After merging the pull request, you could also merge the yt-music branch and update the hooks URL in line 48.

Handle yt and ytm in same package
